name: CI
on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - released

env:
  GCR_REGISTRY: europe-west2-docker.pkg.dev/sml-gke-iac
  GCR_REPOSITORY: scalatimes
  IMAGE: scalatimes

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: softwaremill/sml-gitops/.github/workflows/deploy.yml@main
    with:
      image_path: scalatimes/scalatimes
      context: .
      dockerfile: Dockerfile
      overlay_path: apps/overlays/scalatimes
    secrets: inherit
